import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import connectDB from '@/lib/db';
import Booking from '@/models/Booking';

export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !['admin', 'subadmin'].includes(session.user.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    // 1. Who closed the lead (Lead closures grouped by salesPerson)
    const salesPerformance = await Booking.aggregate([
      { $match: { status: { $in: ['confirmed', 'completed'] }, archived: false } },
      { $group: { _id: '$salesPerson', count: { $sum: 1 }, revenue: { $sum: '$totalAmount' } } },
      { $project: { name: '$_id', count: 1, revenue: 1, _id: 0 } },
      { $sort: { revenue: -1 } }
    ]);

    // 2. Revenue generated by each artist
    const artistPerformance = await Booking.aggregate([
      { $match: { status: { $in: ['confirmed', 'completed'] }, archived: false, artistId: { $exists: true, $ne: null } } },
      { $lookup: { from: 'users', localField: 'artistId', foreignField: '_id', as: 'artist' } },
      { $unwind: { path: '$artist', preserveNullAndEmptyArrays: true } },
      { $group: { 
          _id: '$artistId', 
          artistName: { $first: '$artist.name' },
          performances: { $sum: 1 }, 
          revenueGenerated: { $sum: '$totalAmount' } 
      } },
      { $project: { artistName: 1, performances: 1, revenueGenerated: 1, _id: 0 } },
      { $sort: { revenueGenerated: -1 } }
    ]);

    // 3. Client Satisfaction (Average rating)
    const satisfactionStats = await Booking.aggregate([
      { $match: { clientSatisfactionRating: { $exists: true, $ne: null } } },
      { $group: {
          _id: null,
          averageRating: { $avg: '$clientSatisfactionRating' },
          totalReviews: { $sum: 1 },
          ratingsDistribution: {
            $push: '$clientSatisfactionRating'
          }
      }}
    ]);

    // Calculate rating distribution counts
    let ratingsCount = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
    if (satisfactionStats.length > 0) {
      satisfactionStats[0].ratingsDistribution.forEach((r: number) => {
        if (r >= 1 && r <= 5) ratingsCount[r as keyof typeof ratingsCount]++;
      });
    }

    return NextResponse.json({
      salesPerformance,
      artistPerformance,
      clientSatisfaction: {
        average: satisfactionStats[0]?.averageRating || 0,
        totalReviews: satisfactionStats[0]?.totalReviews || 0,
        distribution: ratingsCount
      }
    });
  } catch (error: any) {
    console.error('Error fetching pipeline stats:', error);
    return NextResponse.json({ error: 'Failed to fetch pipeline stats' }, { status: 500 });
  }
}
